### ISSUE TITLE
Implement auth in better way.

### ISSUE THREAD

**Issue by misha1235000** [misha1235000/serverRegisterClient#13]
### The way it works now
Right now, because I didn't focus on the client side logic, but only its design,
the auth works with a `document.cookie` that is saving the token,
Then the check itself, tests if there are a token, in a way that it just checks the strings length.
Which i think isnt a good way to implement it.

#### The way it need to be
Check if there is a way to check if its a token, easily, and without approaching the server, because, this token is already saved on the `document.cookie`, and if it will expire, it will logout you anyway.

**Comment by shakedmanes** [comment]
I think we can perform that by 2 ways:

1. Change the access token from string to JWT
2. When we asked for resource or something with the token in the request, if the server response with unauthorized or something like that, we redirects the user to logout route.
